// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojoexitafvekloepfnlb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qb2V4aXRhZnZla2xvZXBmbmxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzE5MTksImV4cCI6MjA1OTk0NzkxOX0.5ipqay2EuJY2gEEH3e-fiKcdtbVf09ZOYorhvMbPNpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);